  base_frame_id: robot_footprint
  global_frame_id: map
  odom_frame_id: odom
  odom_model_type: diff-corrected
  transform_tolerance: 0.5
  max_particles: 1000
  min_particles: 100
  laser_model_type: likelihood_field
  laser_sigma_hit: 0.2
  laser_z_hit: 0.99
  laser_z_rand: 0.01
  update_min_a: 0.131
  update_min_d: 0.05
