TrajectoryPlannerROS:

  holonomic_robot: false
  controller_frequency: 5.0
  meter_scoring: true
  pdist_scale: 2.2
  gdist_scale: 2.2
  sim_time: 3.0
  yaw_goal_tolerance: 0.15
  xy_goal_tolerance: 0.30
  min_vel_x: 0.1
  max_vel_x: 2.0
  max_vel_theta: 1.0
  min_in_place_vel_theta: 0.4
  acc_lim_theta: 2.2
  acc_lim_x: 1.0
  acc_lim_y: 1.0
  publish_cost_grid_pc: true
  global_frame_id: odom
  escape_vel: -0.6
