TrajectoryPlannerROS:

  holonomic_robot: false
  controller_frequency: 10.0
  meter_scoring: true
  pdist_scale: 2.2
  gdist_scale: 2.2
  sim_time: 3.0
  yaw_goal_tolerance: 0.15
  xy_goal_tolerance: 0.30
  min_vel_x: 0.1
  max_vel_x: 4.5
  max_vel_theta: 1.0
  min_in_place_vel_theta: 0.4
  acc_lim_theta: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 2.5
  publish_cost_grid_pc: true
  global_frame_id: odom
