TrajectoryPlannerROS:

  holonomic_robot: false
  controller_frequency: 15.0
  meter_scoring: true
  pdist_scale: 2.2
  gdist_scale: 1.8
  sim_time: 2.0
  yaw_goal_tolerance: 0.50
  xy_goal_tolerance: 0.50
  min_vel_x: 0.5
  max_vel_x: 3.0
