map_type: costmap

robot_base_frame: robot_footprint
obstacle_range: 2.5
raytrace_range: 3.0

transform_tolerance: 0.4

footprint: [[-0.1,0.2],[-0.1,-0.2],[0.1,-0.2],[0.1,0.2]]

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /udacity_bot/laser/scan, marking: true, clearing: true}
