global_costmap:
   global_frame: map
   update_frequency: 5.0
   publish_frequency: 5.0
   width: 40.0
   height: 40.0
   resolution: 0.05
   static_map: true
   rolling_window: false
   inflation_radius: 0.2
